# This file was generated by GoReleaser. DO NOT EDIT.
cask "buttons" do
  version "0.59.0"

  on_macos do
    on_intel do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_darwin_x86_64.tar.gz"
      sha256 "8df1a7c30053045c61ff4fcaf53035a27817da789e07f469e37c5025ccd75fa5"
    end
    on_arm do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_darwin_arm64.tar.gz"
      sha256 "92ff34a64a75df9272cfe28fb28195c22c1874b67b82b0c699078b5a532f77d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_linux_x86_64.tar.gz"
      sha256 "a7ad9ace07fe0cdbeed6498701b06cc9c0c17d4acba187f334b5d53bb5937d59"
    end
    on_arm do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_linux_arm64.tar.gz"
      sha256 "5b91b3020f4b9d4bb590f3e426f4599e10da375f411ba13a0cf3b07520c3b295"
    end
  end

  name "buttons"
  desc "Deterministic workflow engine for AI agents"
  homepage "https://buttons.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "buttons"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buttons"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Buttons stores its configuration and run history in ~/.buttons/.

    Get started:
      buttons --help
      buttons create hello --code 'echo hello'
      buttons press hello

    Docs: https://buttons.sh
  EOS
end
