# This file was generated by GoReleaser. DO NOT EDIT.
cask "buttons" do
  version "0.142.0"

  on_macos do
    on_intel do
      sha256 "3f3de62c297ae2dc49cc0b4bd9a049345ddd0e01910a9b0cc888071915e701ad"
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ffa4099740e852c6081e4961151f764fdd19b34d74fc3aa23b6823030036e67f"
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd19f31200421862f7652c8ba889828cc886bae437562fa672ca6f2591344ad4"
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ecf64a36b813fd6889f9a5b84a5259aa20c097dbc5a76f849abbce8c216054ad"
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_linux_arm64.tar.gz"
    end
  end

  name "buttons"
  desc "Deterministic workflow engine for AI agents"
  homepage "https://buttons.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "buttons"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buttons"]
    end
  end
  generate_completions_from_executable "buttons",
    base_name: "buttons",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

  caveats <<~EOS
    Buttons stores its configuration and run history in ~/.buttons/.

    Get started:
      buttons --help
      buttons create hello --code 'echo hello'
      buttons press hello

    Docs: https://buttons.sh
  EOS
end
