# This file was generated by GoReleaser. DO NOT EDIT.
cask "buttons" do
  version "0.82.0"

  on_macos do
    on_intel do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_darwin_x86_64.tar.gz"
      sha256 "9599611b11fc016244147c32ccb4637ccf75721dc514c4fd491b8684302a6b7c"
    end
    on_arm do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_darwin_arm64.tar.gz"
      sha256 "5370892b846a87361da788b3bb97348543a570473ec13ae37cc5eac950700934"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_linux_x86_64.tar.gz"
      sha256 "be1815a92635022a3fd2dacac8771adc6be3acb9ab011e6a2011586198087d24"
    end
    on_arm do
      url "https://github.com/autonoco/buttons/releases/download/v#{version}/buttons_#{version}_linux_arm64.tar.gz"
      sha256 "3420b4a9eeb4f0192baee2e31249a9f5ed9955699253f9d4b4ec49eb5a399123"
    end
  end

  name "buttons"
  desc "Deterministic workflow engine for AI agents"
  homepage "https://buttons.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "buttons"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buttons"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Buttons stores its configuration and run history in ~/.buttons/.

    Get started:
      buttons --help
      buttons create hello --code 'echo hello'
      buttons press hello

    Docs: https://buttons.sh
  EOS
end
